### ISSUE TITLE
AlertModal, ButtonInAlert 컴포넌트 구현

### ISSUE THREAD

**Issue by Ryusoo-h** [Proj-TRENDAR/Frontend#11]
# alert 메세지 출력하는 모달 컴포넌트 만들기
![image](https://github.com/Proj-TRENDAR/Frontend/assets/67295471/945cb068-742f-4e4b-b5f0-5263d9004759)

# 버튼 만들기
모달에 들어갈 버튼을 만들다가.. 비슷한 버튼형태로 여러곳에서 사용될것같아 2가지 size와 3가지 type으로 미리 만들어뒀습니다!
![image](https://github.com/Proj-TRENDAR/Frontend/assets/67295471/494729d4-1d71-4af3-8d11-e3306640a1b0)

**Comment by bkks1004** [comment]
이 페이지 있으니까 좋네요!
